### PR TITLE
Upgrade peer dependencies

### LINKED ISSUE #65: @typescript-eslint/parser@"6.0.0" is out
And this makes impossible to install `eslint-plugin-typescript-sort-keys` then:
```bash
❯ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: biomedit-portal-frontend@6.1.1-dev.7
npm ERR! Found: @typescript-eslint/parser@6.0.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"6.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^1 || ^2 || ^3 || ^4 || ^5" from eslint-plugin-typescript-sort-keys@2.3.0
npm ERR! node_modules/eslint-plugin-typescript-sort-keys
npm ERR!   dev eslint-plugin-typescript-sort-keys@"2.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/christianr/.npm/_logs/2023-07-17T13_44_03_317Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christianr/.npm/_logs/2023-07-17T13_44_03_317Z-debug-0.log
```

### PR DESCRIPTION
**Pull request by thdk**
This is an attempt to fix #65

### CODE REVIEW

**Comment by infctr** [comment]
@thdk thanks for the PR!
Can you have a look at failed checks? Bumping prettier might seem to help

**Comment by thdk** [comment]
Bumped prettier. Removed old eslint rule from jest plugin. Fixed eslint config to only use typescript eslint plugins for typescript files because it will otherwise fail on linting javascript files such as .eslintrc.js which are not included in a tsconfig.json file.

Now some tests still fail on: 

```
  ● Test suite failed to run

    Cannot find module '@typescript-eslint/parser' from 'tests/helpers/configs.ts'

    Require stack:
      tests/helpers/configs.ts
      tests/rules/string-enum.spec.ts

       5 |
       6 | export const typescript: Linter.Config = {
    >  7 |   parser: require.resolve('@typescript-eslint/parser'),
         |                   ^
       8 |   parserOptions: {
       9 |     sourceType: 'module',
      10 |     project: path.join(__dirname, './tsconfig.json'),

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:322:11)
      at Object.<anonymous> (tests/helpers/configs.ts:7:19)
      at Object.<anonymous> (tests/rules/string-enum.spec.ts:5:1)
```

**Comment by thdk** [comment]
Upgraded jest to make tests work.

**Comment by infctr** [comment]
Looks good!

**Review by infctr — APPROVED** [review]

**Comment by infctr** [comment]
Published a new version

**Comment by cpojer** [comment]
Thanks so much for keeping this plugin fresh, I use it in all my projects and recommend it to everyone. It's part of `@nkzw/eslint-config`: https://github.com/cpojer/eslint-config.

**Pull request merged**
